version: 3.3.{build}
branches:
  only:
  - master
image: Visual Studio 2017
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
after_build:
- ps: nuget pack elmah.io.umbraco.nuspec -Version $env:APPVEYOR_BUILD_VERSION -Properties Configuration=Release
artifacts:
- path: '*.nupkg'
deploy:
- provider: NuGet
  api_key:
    secure: 9XpSybqiIbTFiTdfkpUaBSMdLFCm4yx/MYR7KtYbV18g5gP5L6U8bhhOPfi/56o+