name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - uses: nuget/setup-nuget@v1
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
    - name: Restore
      run: nuget restore elmah.io.umbraco.sln
    - name: Build
      run: msbuild elmah.io.umbraco.sln /t:Build /p:Configuration=Release
    - name: Pack Elmah.Io
      run: nuget pack elmah.io.umbraco.nuspec -Version 3.5.${{ github.run_number }}-pre -Properties Configuration=Release
